template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: matrix_repo
    type: GitRepo
    configuration:
      path: deepikasl/multi-source-folder      # Change to your own path
      branches:
        include: ^dynamicMatrix$
      gitProvider: deepikaGithub        # Change to your own GitHub integration name

pipelines:
  - name: matrix_single_dimension_pipeline
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: matrix_repo
        execution:
          onExecute:
            - echo "executing"
            - multiplier=("dog" "goat" "lizard")
            - add_run_variable step_multiplier=multiplier
            
      - name: matrix_step
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: first_step
        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            {{- range $animalName := $step_multiplier }}
            - animal:    {{ $animalName }}       # - Set 1
            {{ end }}
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - echo "Variation animal = ${animal}
