valuesFilePath: ./values.yml
pipelines:
  {{- range $schemaKey, $schemaValue := .Values.services }}
  - name: myRepo_{{ $schemaKey }}
    configuration:
      environmentVariables:
        readOnly:
          configurationNameParam:
            default: test
            description: Configuration name
            values:
              - test
              - test_is
              - prod
              - prod_is
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_deepika
              trigger: false
        execution:
          onExecute:
            - echo "executing first_step"
      - name: second_step
        type: Bash
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - eecho "executing second_step"
  {{ end }}
