resources:
  - name: S_SYC_HBGCleanUp_5933_001_resource
    type: HelmChart
    configuration:
      sourceArtifactory: art
      repository: helm
      chart: app
      version: 0.0.1

pipelines:
  - name: S_SYC_HBGCleanUp_5933_001
    configuration:
      integrations:
        - name: kube
    steps:
      - name: S_SYC_HBGCleanUp_5933_001_1
        type: HelmBlueGreenDeploy
        configuration:
          namespace: namespace
          blueReleaseName: blue
          greenReleaseName: green
          roleServices:
            - blueReferenceName: blueService
              greenReferenceName: greenService
              idleName: idleService
              liveName: liveName
          inputResources:
            - name: S_SYC_HBGCleanUp_5933_001_resource

      - name: S_SYC_HBGCleanUp_5933_001_2
        type: HelmBlueGreenCleanup
        configuration:
          deployStep: S_SYC_HBGCleanUp_5933_001_1
          inputSteps:
            - name: S_SYC_HBGCleanUp_5933_001_1
