resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: branchSnapshot
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: pipelines_build
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: create_repositories
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - echo "executing create_repositories"
      - name: packages_build
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          integrations:
            - name: deepikaGithub
          inputSteps:
            - name: create_repositories
        execution:
          onExecute:
            - echo "executing packages_build"
      - name: templates_build
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - echo "executing templates_build"
      - name: api_build
        type: TriggerPipeline  
        configuration:
          pipelineName:   api_build
          stepName:       api_build
          inputSteps:
            - name: packages_build
            - name: templates_build
          integrations:
            - name: deepikaToken
        execution:
          onStart:
            - echo "executing api_build $pipeline_name"
      - name: www_build
        type: TriggerPipeline  
        configuration:
          pipelineName:   www_build
          stepName:       www_build
          inputSteps:
            - name: packages_build
            - name: templates_build
          integrations:
            - name: deepikaToken
        execution:
          onStart:
            - echo "executing www_build $pipeline_name"
      - name: micro_build
        type: TriggerPipeline  
        configuration:
          pipelineName:   micro_build
          stepName:       micro_build
          inputSteps:
            - name: packages_build
            - name: templates_build
          integrations:
            - name: deepikaToken
        execution:
          onStart:
            - echo "executing micro_build $pipeline_name"
      - name: nodepoolService_build
        type: TriggerPipeline  
        configuration:
          pipelineName:   nodepoolService_build
          stepName:       nodepoolService_build
          inputSteps:
            - name: packages_build
            - name: templates_build
          integrations:
            - name: deepikaToken
        execution:
          onStart:
            - echo "executing nodepoolService_build $pipeline_name"
      - name: createSnapshot
        type: Bash  
        configuration:
          inputSteps:
            - name: api_build
            - name: www_build
            - name: micro_build
            - name: nodepoolService_build
          outputResources:
            - name: branchSnapshot
        execution:
          onExecute:
            - echo "executing createSnapshot"
            
