resources:
  - name: dvu_cron_trigger
    type: CronTrigger
    configuration:
      interval: '0 2 * * *' # Every day at 2 AM
      environmentVariables:
        first: env
        second: env
  
pipelines:
  - name: demo_manual_main
    steps:
      - name: dependency_version_check
        type: Bash
        configuration:
          environmentVariables:
            mySecureEnv:
              allowCustom: true
              secure: true
              default: "someValue"
          inputResources:
            - name: dvu_cron_trigger
        execution:
          onExecute:
            - printenv
