resources:
  - name: propertyBag_deepika
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: myPipeline
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag_deepika
        execution:
          onExecute:
            - echo "first_step"
            - printenv
