resources:
  - name: myRepo_2
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: ^releasePipeline$     
      buildOn:
        branchDelete: true

pipelines:
  - name: sample_skip_pipeline
    steps:
      - name: sample_skip_step
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_2
        execution:
          onExecute:
            - echo "executing"
            - exit 118
            
