resources:
  - name: myRepo_native
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

pipelines:
  - name: myPipeline_native_read
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
        execution:
          onExecute:
            - echo "first_step"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
            - jfrog config add jftest --url https://deepika11921.jfrog-pipelines.com --access-token ${JFROG_LOCAL_ARTIFACTORY_TOKEN}
            - jfrog rt dl deeps-sampleRepo/error.log --flat
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "second_step"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
