resources:  
  - name: myFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: deepikaReadArt
      pattern: "jfrogpipelines/templates/jfrog_name_space/ReleaseTemplate/1.0.0/templateDefinition.yml"
      recursive: false
      flat: true

pipelines:
  - name: deepika_filespec_test
    steps:
      - name: filespec_test
        type: Bash
        configuration:
          inputResources:
            - name: myFileSpec
        execution:
          onExecute:
              - echo "hi"
              
