resources:
  - name: dvu_cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/10 * * * *' # Every 10 minutes
      environmentVariables:
        first: env
        second: env
  
pipelines:
  - name: demo_manual_main
    steps:
      - name: dependency_version_check
        type: Bash
        configuration:
          inputResources:
            - name: dvu_cron_trigger
        execution:
          onExecute:
            - printenv
