resources:
  - name: dvu_cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/2 * * * *' # Every day at 2 AM
  - name: myRepo_1
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      files:
        include: templates\/artifactory\/*|templates\/distribution\/*|templates\/insight\/*|templates\/pipelines\/*|templates\/xray\/*
  - name: newRepo_1
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      files:
        exclude: templates\/artifactory\/*|templates\/distribution\/*|templates\/insight\/*|templates\/pipelines\/*|templates\/xray\/*
  - name: submodule
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: submodule
  - name: submodule_https
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      cloneProtocol: https
      branches:
        include: submodule

  - name: propertyBag_1
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
      storeVersionHistory: false
  
  - name: some_property
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
      storeVersionHistory: false

pipelines:
  - name: another_trigger
    steps:
      - name: deepika_bash_1
        type: Bash
        execution:
          onExecute:
            - echo "hi"
      - name: deepika_bash_2
        type: Bash
        configuration:
          inputSteps:
            - name: deepika_bash_1
        execution:
          onExecute:
            - echo "hi"
  - name: embedded_pipeline_deepika
    steps:
      - name: deepika_bash_1
        type: Bash
        execution:
          onExecute:
            - echo "hi"
      - name: deepika_bash_2
        type: Bash
        configuration:
          inputSteps:
            - name: deepika_bash_1
          outputResources:
            - name: some_property
        execution:
          onExecute:
            - write_output some_property "foo=$run_number"
      - name: deepika_bash_3
        type: Bash
        configuration:
          inputSteps:
            - name: deepika_bash_2
          outputResources:
            - name: some_property
        execution:
          onExecute:
            - write_output some_property "foo1=$run_number"
      - name: deepika_bash_4
        type: Bash
        configuration:
          inputSteps:
            - name: deepika_bash_3
        execution:
          onExecute:
            - echo "here"
  - name: demo_manual_main
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: dependency_version_check
        type: Bash
        configuration:
          affinityGroup: release_group
          inputResources:
            - name: dvu_cron_trigger
        execution:
          onExecute:
            - echo "hi"
      - name: manual_trigger
        type: Bash
        configuration:
          affinityGroup: release_group
          inputResources:
            - name: myRepo_1
          outputResources:
            - name: propertyBag_1
          integrations:
            - name: deepikaGithub
          inputSteps:
            - name: dependency_version_check
        execution:
          onExecute:
            - write_output propertyBag_1 "foo=$run_number"
      - name: submodule_test
        type: Bash
        configuration:
          affinityGroup: release_group
          inputResources:
            - name: newRepo_1
            - name: submodule
            - name: propertyBag_1
              newVersionOnly: true
          inputSteps:
            - name: manual_trigger
        execution:
          onExecute:
            - pushd $res_submodule_resourcePath
            - ls
#       - name: submodule_test_https
#         type: Bash
#         configuration:
#           affinityGroup: release_group
#           inputResources:
#             - name: submodule_https
#             - name: propertyBag_1
#               newVersionOnly: true
#           inputSteps:
#             - name: submodule_test
#         execution:
#           onExecute:
#             - pushd $res_submodule_https_resourcePath
#             - ls
      - name: triggerPipeline
        type: TriggerPipeline
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: newRepo_1
            - name: propertyBag_1
              newVersionOnly: true
          inputSteps:
            - name: submodule_test
          pipelineName: embedded_pipeline_deepika
          stepName: deepika_bash_1
          branchName: releasePipeline
          integrations:
            - name: deepikaPlatform
        execution:
          onStart:
            - pushd $res_newRepo_1_resourcePath
            - ls
      - name: submodule_test_2_trigger
        type: TriggerPipeline
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: newRepo_1
            - name: propertyBag_1
              newVersionOnly: true
          inputSteps:
            - name: triggerPipeline
          pipelineName: another_trigger
          stepName: deepika_bash_1
          branchName: releasePipeline
          integrations:
            - name: deepikaPlatform
        execution:
          onStart:
            - pushd $res_newRepo_1_resourcePath
            - ls
            
