pipelines:
  - name: bi_poc_demo
    configuration:
      affinityGroup: bi_group
      inputResources:
        - name: newRepo_bi
        - name: submodule_bi
    steps:
      - name: vault_check
        type: Bash
        execution:
          onExecute:
            - echo "executing vault_check"
      - name: db_check
        type: Bash
        configuration:
          inputSteps:
            - name: vault_check
        execution:
          onExecute:
            - echo "executing db_check"
      - name: extendend_pipeline
        type: TriggerPipeline
        configuration:
          pipelineName: sub_pipeline_poc
          stepName: first_step
          branchName: {{gitBranch}}
          inputSteps:
            - name: vault_check
        execution:
          onExecute:
            - echo "executing extendend_pipeline"

            
