resources:
  - name: myRepo_2
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: ^releasePipeline$     
      buildOn:
        branchDelete: true
  - name: sample_GitRepo
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/multi-source-folder
      branches:
        include: {{gitBranch}}
      pullRequestTargetBranches:
        include: ^main$
      buildOn:
        commit: {{eq "{{gitBranch}}" main}}
        pullRequestCreate: true
      cancelPendingRunsOn:
        newCommit: true

pipelines:
  - name: matrix_pipe
    steps:
      - name: access_multidb_itest
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - DATABASE_TYPE: postgresql
        configuration:
          multiNode: true
          timeoutSeconds: 2700 # 45 minutes
          inputResources:
            - name: sample_GitRepo
        execution:
          onStart:
            - echo "$IN_PROJECT_ROOT_DIR"
            - set -e
            - echo "$PROJECT_ROOT_DIR"
#             - pushd $IN_PROJECT_ROOT_DIR
          onExecute:
            - echo "executing"
            
