resources:
  - name: S_SYC_HBGDeploy_5978_0006_resource
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: name
      version: '1'

pipelines:
  - name: S_SYC_HBGDeploy_5978_0006
    steps:
      - name: S_SYC_HBGDeploy_5978_0006_1
        type: HelmBlueGreenDeploy
        configuration:
          chartPath: ./
          namespace: namespace
          blueReleaseName: blue
          greenReleaseName: green
          roleServices:
            - blueReferenceName: blueService
              greenReferenceName: greenService
              idleName: idleService
              liveName: liveName
          integrations:
            - name: art
            - name: kube
          inputResources:
            - name: S_SYC_HBGDeploy_5978_0006_resource
        execution:
          onStart:
            - echo "Preparing for work..."
