resources:
  - name: myRepo_1
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

pipelines:
  - name: matrix_pipe
    steps:
      - name: access_multidb_itest
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - DATABASE_TYPE: mariadb
            - DATABASE_TYPE: mssql
            - DATABASE_TYPE: mysql
            - DATABASE_TYPE: oracle
            - DATABASE_TYPE: postgresql
        configuration:
          multiNode: true
          timeoutSeconds: 2700 # 45 minutes
          integrations:
            - name: entArt
          inputResources:
            - name: myRepo_1
          environmentVariables:
            MYSQL_DATABASE_VERSION: "5.7"
            MSSQL_DATABASE_VERSION: "2017-latest"
            ORACLE_DATABASE_VERSION: "18.4.0-slim-faststart-noauto"
            POSTGRESQL_DATABASE_VERSION: "13.4"
            MARIADB_DATABASE_VERSION: "10.1.22"
        execution:
          onStart:
            - task: jfdev-ci-commons/setup-step-commons@v0.0.1
              input:
                JFDEV_CI_COMMONS_DEFAULT_VERSION: 0.0.1
                PROJECT_ROOT_DIR: "${res_myRepo_1_resourcePath}"
            - PROJECT_ROOT_DIR="$res_myRepo_1_resourcePath"
            - echo "$IN_PROJECT_ROOT_DIR"
            - set -e
            - echo "$PROJECT_ROOT_DIR"
#             - pushd $IN_PROJECT_ROOT_DIR
            - pushd $res_myRepo_1_resourcePath
          onExecute:
            - echo "executing"
            
