template: true
valuesFilePath: ../values.yml

resources:
  - name: S_DockerPush_5933_003_GitRepo
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/Org_test_Automation_bash
      branches:
        include: {{gitBranch}}

  - name: S_DockerPush_5933_003_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art

pipelines:
  - name: pipeline_S_DockerPush_5933_003
    configuration:
      outputResources:
        - name: S_DockerPush_5933_003_BuildInfo
    steps:
      - name: S_DockerPush_5933_003_1
        type: DockerBuild
        configuration:
          affinityGroup: S_DockerPush_5933_003
          dockerImageName: ${artifactory_registry_url}/test-automation-docker-local/s_dockerpush_5933
          dockerImageTag: ${run_id}
          inputResources:
            - name: S_DockerPush_5933_003_GitRepo
          integrations:
            - name: s_artifactory
      - name: S_DockerPush_5933_003_2
        type: DockerPush
        configuration:
          affinityGroup: S_DockerPush_5933_003
          targetRepository: test-automation-docker-local
          autoPublishBuildInfo: true
          inputSteps:
            - name: S_DockerPush_5933_003_1
          integrations:
            - name: s_artifactory
