resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: myPipeline
    configuration:
      chronological: true
      inputResources:
        - name: myRepo
          trigger: false
    steps:
      - name: first_step
        type: Bash          
        execution:
          onExecute:
            - echo "first_step"
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "second_step"
            - echo "logic to be put from onComplete section"
      - name: third_step
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                registry: docker #integration name
                name: entplus.jfrog.io/devops-docker/jfrog/devops/jfrog-saas-deployer
                tag: "latest"
                autoPull: true
                options: --entrypoint=""
          inputSteps:
            - name: second_step
          integrations:
            - name: deepikaTestIntegration
            - name: firstIntdeepikapipe
            - name: anotherIntegration
            - name: secondInt
          outputResources:
            - name: propertyBag
        execution:
          onStart:
            - javac -version
            - mvn --version
          
            
