
resources:
  - name: dvu_cron_trigger
    type: CronTrigger
    configuration:
      interval: '* 2 * * *' # Every day at 2 AM
  - name: myRepo_1
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      files:
        include: templates\/artifactory\/*|templates\/distribution\/*|templates\/insight\/*|templates\/pipelines\/*|templates\/xray\/*
  - name: propertyBag_1
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
      storeVersionHistory: false

pipelines:
  - name: jfdev_ci_commons_release
    configuration:
      environmentVariables:
        readOnly:
          SLACK_RELEASE_INTEGRATION_CHANNEL:
            default: jfdev-ci-common-release-pipeline
          CI:
            default: 'true'
            description: >-
              [DO_NOT_CHANGE] disables interactive prompts and progress bar for the
              JFrog CLI
          SKIP_STEP_STATUS_UPDATE:
            default: 'true'
            description: '[DO_NOT_CHANGE] Skips step status update to bitbucket'
            values:
              - 'true'
              - 'false'
          SERVICES_TO_RELEASE:
            default: jfdev_ci_commons
            values:
              - jfdev_ci_commons
          PIPELINE_GIT_PUSH_SSH_INTEGRATION:
            default: deepikaArt
            values:
              - deepikaArt
          SERVICE_GIT_REPO_PATH:
            default: auto/jfdev-ci-commons
            values:
              - auto/jfdev-ci-commons
          GIT_LFS_SKIP_SMUDGE:
            default: 'true'
            description: Git LFS skip the smudge process
          SERVICE_DISPLAY_NAME:
            default: JFDev CI Commons
            values:
              - JFDev CI Commons
          SERVICE_BUILD_PIPELINE:
            default: jfdev_ci_commons_build
            values:
              - jfdev_ci_commons_build
          SERVICE_POST_RELEASE_PIPELINE:
            default: jfdev_ci_commons_post_release
            values:
              - jfdev_ci_commons_post_release
          RELEASE_MINOR:
            default: 'false'
            description: Compute the next version as a minor
            values:
              - 'true'
              - 'false'
          SERVICE_BUILD_PIPELINE_FIRST_STEP:
            description: Defining the first step of the Build Pipeline
            default: trigger_all
            values:
              - trigger_all
              - trigger_post_release
          MILESTONE_TAG:
            default: ''
            values:
              - ''
              - 'false'
            description: >-
              [MANDATORY]: Flag to determine the type of the release, options
              are:<br> release a milestone) Value should be an empty string<br>
              release an official version from a milestone) Value should be set to
              the milestone tag (e.g artifactory/7.24.0-m013) you aim to release
              from (will shorten the release cycle)<br> release an official version
              without a milestone) Value should be set to false
            allowCustom: true
    steps:
      - name: create_release_branch
        type: Bash
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: myRepo_1
              trigger: false
            - name: dvu_cron_trigger
              trigger: true
          integrations:
            - name: deepikaArt
        execution:
          onStart:
            - echo "here"
      - name: select_and_modify_release_versions
        type: Bash
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: myRepo_1
              trigger: false
          inputSteps:
            - name: create_release_branch
          integrations:
            - name: deepikaArt
          outputResources:
            - name: propertyBag_1
        execution:
          onStart:
            - echo "here"
      - name: wait_for_branch_sync
        type: Bash
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: myRepo_1
              trigger: false
            - name: propertyBag_1
              newVersionOnly: true
        execution:
          onStart:
            - echo "here"
      - name: build_release_artifacts
        type: Bash
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: myRepo_1
              trigger: false
            - name: propertyBag_1
              newVersionOnly: true
          inputSteps:
            - name: wait_for_branch_sync
        execution:
          onStart:
            - echo "here"
      - name: post_release_actions
        type: Bash
        configuration:
          nodePool: u18dynamic
          affinityGroup: release_group
          priority: 1
          inputResources:
            - name: myRepo_1
              trigger: false
            - name: propertyBag_1
              newVersionOnly: true
          inputSteps:
            - name: build_release_artifacts
        execution:
          onStart:
            - echo "here"
