valuesFilePath: ./values.yml

resources:
  - name: xsc_aql_rb
    type: Aql
    configuration:
      sourceArtifactory: deepikaArt
      query: "items.find({
\"$and\": [
      {
        \"$or\": [
          {
            \"repo\": {
              \"$eq\": \"xsc-docker-sc-service-local\"
            }
          }
        ]
      },
      {
        \"$or\": [
          {
            \"path\": {
              \"$match\": \"*jfrog/xsc-service/0.0.130*\"
            }
          }
        ]
      }      
    ]
}).include(\"sha256\",\"updated\",\"modified_by\",\"created\",\"id\",\"original_md5\",\"depth\",\"actual_sha1\",\"property.value\",\"modified\",\"property.key\",\"actual_md5\",\"created_by\",\"type\",\"name\",\"repo\",\"original_sha1\",\"size\",\"path\")"
 
pipelines:
  - name: test_sample_pipeline
    steps:
      - name: first_step
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: "deepika-test-sign"
          inputResources:
            - name: xsc_aql_rb
        execution:
          onExecute:
            - echo "executing"
