valuesFilePath: ./values.yaml
  {{ $schemaKey := "jira_cloud" }}
pipelines:
  - name: birepo_{{ $schemaKey }}
    configuration:
      affinityGroup: jfrogbi_image
      environmentVariables:
        readOnly:
          configurationName:
            default: test_is
            description: Configuration name
            values:
              - test
              - test_is
              - prod
              - prod_is
      runtime:
        type: host
    steps:
      - name: vault_conf
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: biinfra_git_src
              trigger: false
            - name: birepo_git_src
              trigger: false
        execution:
          onExecute:
            - |
              if [ "$configurationName" == "prod" ]; then
                add_run_variables rsDb="redshift-etl"
                add_run_variables envName="prod"
              elif [ "$configurationName" == "prod_is" ]; then
                add_run_variables rsDb="rs-etl-is"
                add_run_variables envName="prod"
              else
                add_run_variables rsDb="rs-etl-is"
                add_run_variables envName="test"
              fi
            - add_run_variables vaultUser="kaholo-ci"
            - mkdir -p /workspace/birepo
            - mkdir -p /workspace/biinfra
            - cp -rf $res_birepo_git_src_resourcePath/* /workspace/birepo
            - cp -rf $res_biinfra_git_src_resourcePath/* /workspace/biinfra
            - cd /workspace/birepo
            - |
              export VAULT_TOKEN=$int_jfrog_vault_jfrog_ci_vault_token && >-
              export VAULT_ADDR="https://vault.jfrog.org" && >-
              export SDM_ADDRESS="127.0.0.1" && >-
              /workspace/birepo/run.sh -env ${envName} conf vault read --vault_user ${vaultUser} --defaults
          onComplete:
            - echo "Complete vault_conf on Branch {{gitBranch}}!"
            - cp -rf /workspace/* $shared_workspace
      - name: docker_agent_build
        type: Bash
        configuration:
          inputSteps:
            - name: vault_conf
        execution:
          onExecute:
            - cd $shared_workspace/biinfra
            - docker login -u $int_jfrogbiart_user -p $int_jfrogbiart_apikey jfrogbi-docker.jfrog.io
            - echo "did login"
          onComplete:
            - echo "complete step"
      - name: db_check
        type: Bash
        configuration:
          inputSteps:
            - name: docker_agent_build
        execution:
          onExecute:
            - cd $shared_workspace/birepo
            - ./run.sh -env ${envName} db check
          onComplete:
            - echo "Complete db_check on Branch {{gitBranch}}!"
      {{- range $tableKey, $tableValue := .Values.jira_cloud_tables }}
      - name: {{ $tableKey }}
        type: Bash
        configuration:
          priority: {{ $tableValue.priority }}
          inputSteps:
            - name: db_check
        execution:
          onExecute:
            - cd $shared_workspace/birepo
            - |
              if [ "{{ $tableValue.type }}" == "import" ]; then
                add_run_variables execCmd="./run.sh -env ${envName} exec import {{ $schemaKey }} {{ $tableKey }} --rs_db ${rsDb}"
              elif [ "{{ $tableValue.type }}" == "etl" ]
                add_run_variables execCmd="./run.sh -env ${envName} exec etl {{ $schemaKey }} {{ $tableKey }} --rs_db ${rsDb}"
              else
                add_run_variables execCmd="./run.sh -env ${envName} exec export {{ $tableKey }} --rs_db ${rsDb}"
              fi
            - ${execCmd}
          onComplete:
            - echo "Complete running {{ $schemaKey }}:{{ $tableKey }} on Branch {{gitBranch}}!"
      {{ end }}
      {{- range $tableKey, $tableValue := .Values.jira_cloud_etl_tables }}
      - name: {{ $tableKey }}
        type: Bash
        configuration:
          priority: {{ $tableValue.priority }}
          inputSteps:
            - name: {{ sub $tableValue.priority 1 }}
        execution:
          onExecute:
            - cd $shared_workspace/birepo
            - ${execCmd}
          onComplete:
            - echo "Complete running {{ $schemaKey }}:{{ $tableKey }} on Branch {{gitBranch}}!"
      {{ end }}
