resources:
  - name: propertyBag_deepika
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: prop_repo
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: {{gitBranch}}

pipelines:
  - name: myPipeline_pb
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag_deepika
            - name: prop_repo
        execution:
          onExecute:
            - echo "first_step"
            - echo "$foo"
            - printenv
