resources:
  - name: sample_repo
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^master$       

pipelines:
  - name: sample_pipeline_deepika
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: int_default_artifactory
          inputResources:
            - name: sample_repo
        execution:
          onStart:
            - task: jira-transition@v0.0.9
              input:
                issue_key: TAS-1
                jira_integration_name: deepikajira
                transition_name: To Do
          onExecute:
            - echo "executing"
            
