resources:  
  - name: myFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: deepikaArt
      pattern: "jfrogpipelines/templates/jfrog_name_space/ReleaseTemplate/1.0.0/templateDefinition.yml"
      recursive: false
      flat: true
      
  - name: myAql
    type: aql
    configuration:
      sourceArtifactory: deepikaArt
      query: 'items.find({"repo":"jfrogpipelines","name":{"$match":"*.json"}})'
#       aql: 'items.find({"repo":"version-stg","name":{"$match":"host-*.json"}}).sort({"$desc":["updated"]}).limit(1)'
#       aql: '{"@build.name":{"$eq":"artifactory"}}'
#       aql: '{"repo":"jfrogpipelines","name":{"$match":"*.yml"}}'
  
  - name: myFileSpecAql
    type: FileSpec
    configuration:
      sourceArtifactory: deepikaArt
#       aql: 'items.find({"repo":"version-stg","name":{"$match":"host-*.json"}}).sort({"$desc":["updated"]}).limit(1)'
#       aql: '{items.find({"@build.name":{"$eq":"artifactory"}})}'
        aql: '{"repo":"jfrogpipelines","name":{"$match":"*.yml"}}'
#       aql: myAql

pipelines:
  - name: deepika_filespec_test
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: filespec_test
        type: Bash
        configuration:
          inputResources:
            - name: myFileSpecAql
        execution:
          onExecute:
              - echo "hi"
              
