resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: myPipeline
    steps:
      - name: first_step
        type: Bash          
        execution:
          onExecute:
            - echo "first_step"
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "second_step"
            - echo "logic to be put from onComplete section"
      - name: third_step
        type: Bash
        configuration:
          condition: '{{gitBranch}} == master'
          inputResources:
            - name: myRepo
          inputSteps:
            - name: second_step
          integrations:
            - name: deepikaTestIntegration
        execution:
          onStart:
            - javac -version
            - mvn --version
          
            
