resources:
  - name: ei2095_docker_dev_artifact_test
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepika_jfrog
      repositories:
        - docker-dev-deepika
      buildOn:
        deployed: true
      branches:
        include: "^.+$"
  - name: ei2095_docker_dev_artifact_test_2
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepika_jfrog
      repositories:
        - docker-dev-deepika_gen
      buildOn:
        deployed: true
      branches:
        include: "^.+$"

pipelines:
  - name: ei2095_iotics_node_package
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: ei2095_docker_dev_artifact_test
            - name: ei2095_docker_dev_artifact_test_2
        execution:
          onExecute:
            - printenv
