resources:  
  - name: myFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: readArt
      pattern: "jfrogpipelines/pipelines-template"
      recursive: false
      flat: true

pipelines:
  - name: deepika_filespec_test
    configuration:
    steps:
      - name: filespec_test
        type: Bash
        configuration:
          inputResources:
            - name: myFileSpec
        execution:
          onExecute:
              - echo "hi"
              
