resources:
  - name: propertyBag_e
    type: PropertyBag
    configuration:
      foo: bar
  - name: propertyBag1_e
    type: PropertyBag
    configuration:
      foo1: bar1
  - name: propertyBag2
    type: PropertyBag
    configuration:
      foo2: bar2
  - name: propertyBag3
    type: PropertyBag
    configuration:
      foo3: bar3


pipelines:
  - name: pipeline1
    steps:
      - name: first_step
        type: Bash  
        configuration:
          outputResources:
            - name: propertyBag_e
        execution:
          onExecute:
            - write_output propertyBag_e "foo=$run_number" 
  - name: pipeline2
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag_e
          outputResources:
            - name: propertyBag1_e
        execution:
          onExecute:
            - write_output propertyBag1_e "foo1=$run_number"
  - name: pipeline3
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag1_e
        execution:
          onExecute:
            - echo "executing"
  - name: pipeline4
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag1_e
          outputResources:
            - name: propertyBag2
        execution:
          onExecute:
            - write_output propertyBag2 "foo2=$run_number" 
  - name: pipeline5
    configuration:
      dependencyMode:
        waitOnParentComplete: true
        waitOnChildComplete: true
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag2
          outputResources:
            - name: propertyBag3
        execution:
          onExecute:
            - write_output propertyBag3 "foo3=$run_number"
  - name: pipeline6
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag3
        execution:
          onExecute:
            - echo "executing pipeline6"
  - name: pipeline7
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag3
        execution:
          onExecute:
            - echo "executing pipeline7"


          
            
