resources:
  - name: S_HelmDeploy_ReleaseBundle_0027_ReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: name
      version: '1'

pipelines:
  - name: pipeline_S_HelmDeploy_0027
    steps:
      - name: S_HelmDeploy_0027
        type: HelmDeploy
        configuration:
          helmVersion: 3
          releaseName: release
          chartPath: ./helmCharts/
          integrations:
            - name: art
            - name: kube
          inputResources:
            - name: S_HelmDeploy_ReleaseBundle_0027_ReleaseBundle
