resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      files:
        include: templates\/artifactory\/*|templates\/distribution\/*|templates\/insight\/*|templates\/pipelines\/*|templates\/xray\/*
  - name: newRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      files:
        exclude: templates\/artifactory\/*|templates\/distribution\/*|templates\/insight\/*|templates\/pipelines\/*|templates\/xray\/*
  - name: submodule
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: submodule
  - name: submodule_https
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      cloneProtocol: https
      branches:
        include: submodule

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual_main
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          outputResources:
            - name: propertyBag
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
      - name: submodule_test
        type: Bash
        configuration:
          inputResources:
            - name: newRepo
            - name: submodule
          inputSteps:
            - name: manual_trigger
        execution:
          onExecute:
            - pushd $res_submodule_resourcePath
            - ls
            - pushd myFirstSubModule
            - ls
      - name: submodule_test_https
        type: Bash
        configuration:
          inputResources:
            - name: submodule_https
          inputSteps:
            - name: manual_trigger
        execution:
          onExecute:
            - pushd $res_submodule_https_resourcePath
            - ls
            - pushd myFirstSubModule
            - ls
  - name: second_pipeline
    steps:
      - name: submodule_test
        type: Bash
        configuration:
          inputResources:
            - name: newRepo
        execution:
          onExecute:
            - pushd $res_newRepo_resourcePath
            - ls
            - pushd myFirstSubModule
            - ls
            
