resources:
  - name: testInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: 'name'
      buildNumber: '1'

pipelines:
  - name: pipeline
    configuration:
      nodePool: k8s
    steps:
      - name: mystep
        type: Bash
        execution:
          onExecute:
            - echo "executing..."
