resources:
  - name: dvu_cron_trigger_1
    type: CronTrigger
    configuration:
      interval: '* 2 * * *' # Every day at 2 AM
  
pipelines:
  - name: demo_manual_main_pre
    preRun: 
      execution: 
        onExecute: 
          - printenv 
          - echo "Executing Pre Run"
    steps:
      - name: dependency_version_check
        type: Bash
        configuration:
          inputResources:
            - name: dvu_cron_trigger_1
        execution:
          onExecute:
            - echo "hi"
