resources:
  - name: dvu_cron_trigger
    type: CronTrigger
    configuration:
      interval: '* 2 * * *' # Every day at 2 AM
      environmentVariables:
        first: env
        second: env
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  
pipelines:
  - name: demo_manual_main
    steps:
      - name: dependency_version_check
        type: Bash
          inputResources:
            - name: dvu_cron_trigger
            - name: propertyBag
        execution:
          onExecute:
            - printenv
