template: true
valuesFilePath: ./values.yml

resources:
  - name: myRepo_template
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: {{ .Values.GitRepo.gitProvider }}
      branches:
        include: master
      buildOn:
        pullRequestCreate: {{ regexMatch ".*renovatebot.*" `{{"{{gitBranch}}"}}` }}

  - name: propertyBag_template
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual_template
    configuration:
      environmentVariables:
        readOnly:
          GIT_INT: {{ .Values.GitRepo.gitProvider }}
      integrations:
        - name: deepikaGithub
    steps:
      - name: manual_trigger_template
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_template
          outputResources:
            - name: propertyBag_template
          integrations:
            - name: deepikaGithub
        execution:
          onStart:
            - task: jfdev-ci-commons/setup-step-commons@v0.0.1
              input:
                JFDEV_CI_COMMONS_DEFAULT_VERSION: {{ .Values.jfdevCiCommonsDefaultVersion }}
                PROJECT_ROOT_DIR: "${res_observability_pre_releases_process_bitbucket_resourcePath}"
              id: setup_step_commons
            - |
              if [ "{{gitBranch}}" = "main" ]; then
                echo "Branch is 'main'"
              fi
          onExecute:
#             - write_output propertyBag "foo=$run_number"
            - echo "here"
            - git config --list
            
