resources:
  - name: propertyBag_e
    type: PropertyBag
    configuration:
      foo: bar
  - name: propertyBag1_e
    type: PropertyBag
    configuration:
      foo1: bar1
  - name: propertyBag2
    type: PropertyBag
    configuration:
      foo2: bar2
  - name: propertyBag3
    type: PropertyBag
    configuration:
      foo3: bar3


pipelines:
  - name: pipeline1
    steps:
      - name: first_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline2
          stepName:       first_step
          waitForRunCompletion: false
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing first_step $pipeline_name"
  - name: pipeline2
    steps:
      - name: first_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline3
          stepName:       first_step
          waitForRunCompletion: false
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing first_step $pipeline_name"
      - name: second_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline4
          stepName:       first_step
          waitForRunCompletion: false
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing second_step $pipeline_name"
  - name: pipeline3
    steps:
      - name: first_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline4
          stepName:       first_step
          waitForRunCompletion: false
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing first_step $pipeline_name"
  - name: pipeline4
    steps:
      - name: first_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline5
          stepName:       first_step
          waitForRunCompletion: false
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing first_step $pipeline_name"
  - name: pipeline5
    steps:
      - name: first_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline6
          stepName:       first_step
          waitForRunCompletion: true
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing first_step $pipeline_name"
      - name: second_step
        type: TriggerPipeline  
        configuration:
          pipelineName:   pipeline7
          stepName:       first_step
          waitForRunCompletion: true
          integrations:
            - name: deepikaArt
        execution:
          onExecute:
            - echo "executing second_step $pipeline_name"
  - name: pipeline6
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag3
        execution:
          onExecute:
            - echo "executing pipeline6"
  - name: pipeline7
    steps:
      - name: first_step
        type: Bash  
        configuration:
          inputResources:
            - name: propertyBag3
        execution:
          onExecute:
            - echo "executing pipeline7"


          
            
