resources:
  - name: myRepo_1
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

pipelines:
  - name: demo_manual_main
    configuration:
      environmentVariables:
        readOnly:
          pipelineEnv:
            default: "somePipValue"
      integrations:
        - name: deepikaGithub
    steps:
      - name: dependency_version_check
        type: Bash
        configuration:
          environmentVariables:
            mySampleEnv:
              allowCustom: true
              default: "someValue"
          inputResources:
            - name: myRepo_1
        execution:
          onExecute:
            - printenv

