resources:
  - name: Input_TIA
    type: GitRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: master 
  - name: Output_TIA
    type: BuildInfo
    configuration:
      sourceArtifactory: deepikaArt
pipelines:
  - name: pipeline_Test_IMOnline_APICore
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: ecomm-mvn-coreapi-libs-snapshot-local
          deployerReleaseRepo: ecomm-mvn-coreapi-libs-release-local
          inputResources:
            - name: Input_TIA
          integrations:
            - name: deepikaArt
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: True
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: Output_TIA
