resources:
  - name: myRepo_native_write
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

pipelines:
  - name: myPipeline_native_write
    steps:
      - name: first_step
        type: Bash
        configuration:
          integrations:
            - name: {{.jfrog-pipelines.localArtifactory}}
        execution:
          onExecute:
            - echo "first_step"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
            - sudo jfrog config add jftest --url http://localhost:8082 --access-token ${JFROG_LOCAL_ARTIFACTORY_TOKEN}
            - touch test.txt
            - echo "hello" > test.txt
            - sudo jfrog rt upload test.txt deeps-sampleRepo/test.txt
      - name: second_step
        type: Bash   
        configuration:
          inputSteps:
            - name: first_step
        execution:
          onExecute:
            - echo "second_step"
            - echo "$JFROG_LOCAL_ARTIFACTORY_TOKEN"
