 GitRepo:
  name: myRepo
  gitProvider: deepikaGithub
  path: deepikasl/jfrog-pipelines
  branches:
    include: master
   
 Bash:
   onExecuteTest:
     - write_output propertyBag "foo=$run_number"
     - echo "here"
