metadata:

  serviceName:  api

  node: "18"

inputs:
  pipeline:
    configuration:
      integrations:
        - deepikaArt
        - mySlack
      environmentVariables:
        foo: bar
        test: env
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 90

  sourceRepository:
    path: deepikasl/jfrog_pipelines
    gitProvider: deepikaGithub
    branches:
      include: master

  integrations:

    artifactory: deepikaArt
    sonar: deepikaSonar

configurations:

  sourceDirectory: ''

  steps:

    codeQuality:

      commands:
        - npm run lint:api


    sonarScan:

      commands:
        - npm run build


    build:

      commands:
        - npm run build


    publish:

      commands:
        - jfrog rt publish


    clamScan:

      commands:
        - npm run build
        

controls:

  enableQuality: true
  isPublishAvailable: true

  triggerBy:
    sourceRepository: true


  # [Optional] Enable notifications
  notifications:
    email:
      integrationName: 'mySMTP' # SMTP
      content: ''

    slack:
      integrationName: 'mySlack'
      content: ''
