templateRepository:
  gitProvider: deepikaGithub
  path: deepikasl/old-templates
  branch: main
  templateFolder: templates/jfrog_name_space/myPipelineTemplate
 
publishTemplate:
  namespace: deepikaTemplates
  name: myPipelineTemplate
  version: 1.0.0
  pipelineName: PublishTemplate
  artifactoryIntegration: deepikaArt
