metadata:

  serviceName:  api

  node: "16"

inputs:

  sourceRepository:
    path: deepikasl/jfrog-pipelines
    gitProvider: deepikaGithub
    branches:
      include: master

  integrations:

    artifactory: deepikaArt
    sonar: deepikaSonar

configurations:

  sourceDirectory: ''

  steps:

    codeQuality:

      commands:
        - 'npm run lint:api'


    sonarScan:

      commands:
        - 'some command'


    build:

      commands:
        - 'npm run build'


    publish:

      commands:
        - 'jfrog rt publish'


    clamScan:

      commands:
        - 'npm run build'
        

controls:

  enableQuality: true
  isPublishAvailable: true

  triggerBy:

    # Connected source Git repository change [Defaults to true]
    sourceRepository: true

    # Other resource change from other pipelines
    # externalResources:
    #   - resourceName: dream_app_commons_build_result

    # Incoming webhook
    # incomingWebhooks:
    #   - webhookName: 'testWebhook' # IncommingWebhook integration name


  # [Optional]
  logging:

    # [Optional] Defaults to false
    enableDebug: true

  # [Optional] Exporting important files during run as RUN FILES
  exporting:

    # [Optional] Defaults to false
    enabled: true

  # [Optional] Enable notifications
  notifications:
    email:
      integrationName: 'mySMTP' # SMTP
      content: ''

    slack:
      integrationName: 'mySlack'
      content: ''
