metadata:

  serviceName:  api

  node: "18"

inputs:
  pipeline:
    configuration:
      integrations:
        - deepikaArt
        - mySlack
      environmentVariables:
        foo: bar
        test: env
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10

  sourceRepository:
    path: deepikasl/jfrog_pipelines
    gitProvider: deepikaGithub
    branches:
      include: master

  integrations:

    artifactory: deepikaArt
    sonar: deepikaSonar

configurations:

  sourceDirectory: ''

  steps:
    build:
      onStart:
        - cd $shared_workspace

      onExecute:
        - npm run build

      onFailure:
        - send_notification

      onSuccess:
        - send_notification

    codeQuality:
      onExecute:
        - npm run lint:api


    sonarScan:
      onStart:
        - npm run build

      onExecute:
        - npm run build


    publish:
      onExecute:
        - jfrog rt publish


    clamScan:
      onExecute:
        - npm run build
        

controls:

  enableQuality: true
  isPublishAvailable: true

  triggerBy:
    sourceRepository: true
