metadata:
  serviceName:  api
  node: "18"

inputs:
  pipeline:
    configuration:
      integrations:
        - deepikaArt
        - mySlack
      environmentVariables:
        foo: bar
        test: env
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10

  sourceRepository:
    path: deepikasl/jfrog_pipelines
    gitProvider: deepikaGithub
    branches:
      include: master

  integrations:
    artifactory: deepikaArt
    sonar: deepikaSonar

configurations:

  sourceDirectory: ''

  steps:
    build:
      runtime:
        versions:
          - "16.10.0"
      onStart:
        - on_start
      onExecute:
        - npm run build
      onFailure:
        - send_notification
      onSuccess:
        - send_notification

    codeQuality:
      onStart:
        - npm run build
      onExecute:
        - npm run lint:api
      onFailure:
        - send_notification
      onSuccess:
        - send_notification


    sonarScan:
      onStart:
        - npm run build
      onExecute:
        - on_execute
      onFailure:
        - send_notification
      onSuccess:
        - send_notification

    publish:
      onExecute:
        - jfrog rt publish
      onFailure:
        - send_notification
      onSuccess:
        - send_notification


    clamScan:
      onStart:
        - npm run build
      onExecute:
        - on_execute
      onFailure:
        - send_notification
      onSuccess:
        - send_notification
        
controls:

  build:
    runtime: auto

  codeQuality:
    enabled: true

  publish:
    enabled: true

  enableQuality: true
  enablePublish: true

  triggerBy:
    sourceRepository: true
