 GitRepo:
  name: myRepo
  gitProvider: deepikaGithub
  path: deepikasl/jfrog-pipelines
  branches:
    include: master
  jfdevCiCommonsDefaultVersion: 1.42.*
   
 Bash:
   onExecuteTest:
     - write_output propertyBag "foo=$run_number"
     - echo "here"
     - git config --list
